//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WageCalculator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.ComponentModel;

    public partial class StaffMember
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "A name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "An hourly rate is required")]
        public double HourlyRate { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double MonHours { get; set; } = 0;
        public double MonPay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double TueHours { get; set; }
        public double TuePay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double WedHours { get; set; }
        public double WedPay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double ThuHours { get; set; }
        public double ThuPay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double FriHours { get; set; }
        public double FriPay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double SatHours { get; set; }
        public double SatPay { get; set; }
        [Range(0, 16, ErrorMessage = "Amount of hours must be between 0 and 16")]
        public double SunHours { get; set; }
        public double SunPay { get; set; }
        public double TotalHours { get; set; }
        public double TotalPay { get; set; }
    }
}
